---
title: "Testing various plot functions"
output: html_notebook
---

```{r}
source("global.R")
```

```{r}
display_x  <- panimmune_data$sample_selection_choices[1]
display_y  <- panimmune_data$cell_content_choices[1]
internal_x <- get_variable_internal_name(display_x)
internal_y <- get_variable_internal_name(display_y)

plot_df <- panimmune_data$df %>% 
    select_(.dots = c(internal_x, internal_y)) %>% 
    .[complete.cases(.),]

plot <- create_violinplot(
    plot_df,
    internal_x,
    internal_y,
    internal_x,
    xlab = display_x,
    ylab = display_y,
    fill_colors = decide_plot_colors(panimmune_data, internal_x)
)
plot
```




```{r}
pal <- c(C1 = "red", C2 = "yellow", C3 = "green", C4 = "cyan", C5 = "blue", C6 = "magenta")
plot_df %>% 
    plot_ly(
        x = ~Subtype_Immune_Model_Based,
        y = ~leukocyte_fraction,
        split = ~Subtype_Immune_Model_Based,
        color = ~Subtype_Immune_Model_Based,
        colors = pal,
        type = 'violin',
        box = list(
            visible = T
        ),
        meanline = list(
            visible = T
        )
    )
```

```{r}
plot_df <- panimmune_data$df %>% 
    create_scatterplot_df(
        "Subtype_Immune_Model_Based",
        "C4",
        "Dendritic_cells.Aggregate2",
        "leukocyte_fraction"
    )

head(plot_df)
```

```{r}
let(
   alias = c(
       xvar = "leukocyte_fraction",
       yvar = "Dendritic_cells.Aggregate2"
   ),
    plot_df %>% 
        plot_ly(
            x = ~xvar,
            y = ~yvar
    ) %>% 
       layout(
           title = "C6",
           xaxis = list(title = "Leukocyte Fraction"),
           yaxis = list(title = "Macrophages")
       )
)
```

