module_files:
  - "modules/dashboardmodule.R"
  - "modules/cellcontentmodule.R"
  - "modules/immuneinterfacemodule.R"
  - "modules/featurecorrelationmodule.R"
  - "modules/survivalmodule.R"
  - "modules/immunomodulatormodule.R"
  - "modules/datainfomodule.R"
  
function_files:
  - "functions/load_data.R"
  - "functions/transform.R"
  - "functions/drilldown.R"
  - "functions/utils.R"
  - "functions/boxplot.R"
  - "functions/heatmap.R"
  - "functions/kmplot.R"
  - "functions/histogram.R"
  - "functions/format.R"
  - "functions/scatterplot.R"
  - "functions/violinplot.R"
  - "functions/mosaicplot.R"

page_files:
  - "pages/aboutpage.R"
  - "pages/explorepage.R"
  - "pages/docspage.R"
  - "pages/resourcespage.R"

libraries:
  - "shinythemes"
  - "bigrquery"
  - "plotly"
  - "heatmaply"
  - "survival"
  - "survminer"
  - "googlesheets"
  - "feather"
  - "shinydashboard"
  - "ggmosaic"
 
bq_remote: false # set data as remote (BigQuery) or local (on disk)
gs_remote: false
  
cell_content_local:
  - "leukocyte_fraction"
  - "Lymphocytes.Aggregate1"
  - "T.cells.CD8"
  - "T_cells_CD4.Aggregate2"
  - "Macrophage.Aggregate1"

cell_content_bq:
  - "leukocyte_fraction"
  - "Lymphocytes.Aggregate1"
  - "T_cells_CD8"
  - "T_cells_CD4_Aggregate2"
  - "Macrophage_Aggregate1"
 
diversity_metric_choices:
  - "Evenness"
  - "Shannon"
  - "Richness"

receptor_type_choices:
  - "TCR"
  - "BCR"
  
immunomodulator_groups:
  - "Gene_Family"
  - "Super_Category"
  - "Immune_Checkpoint"
  - "Function"
