source_files:
  - "modules/cellcontentmodule.R"
  - "modules/immuneinterfacemodule.R"
  - "modules/featurecorrelationmodule.R"
  - "modules/survivalmodule.R"
  - "functions/load_data.R"
  - "functions/utils.R"
  - "functions/boxplot.R"
  - "functions/heatmap.R"
  - "functions/kmplot.R"

libraries:
  - "shinythemes"
  - "bigrquery"
  - "plotly"
  - "heatmaply"
  - "survival"
  - "survminer"
  - "googlesheets"

Leukocytes:
   - "Neutrophils.Aggregate2"
   - "Eosinophils.Aggregate2"
   - "Mast_cells.Aggregate2"
   - "Dendritic_cells.Aggregate2"
   - "Macrophage.Aggregate2"
   - "NK_cells.Aggregate2"
   - "B_cells.Aggregate2"
   - "T_cells_CD8.Aggregate2"
   - "T_cells_CD4.Aggregate2"
   
Gene Sets:   
   - "CHANG_CORE_SERUM_RESPONSE_UP"
   - "CSF1_response"
   - "LIexpression_score"
   - "Module3_IFN_score"
   - "TGFB_score_21050467"
   
Genes RNA-seq & RPPA:
   - "CD274_RNASeq"
   - "CD68_RNASeq"
   - "CD8A_RNASeq"
   - "CTLA4_RNASeq"
   - "PDCD1_RNASeq"
   - "TREM1_RNASeq"
   - "CD274_RPPA"
   - "CTLA4_RPPA"
   - "LCK_RPPA"
   - "PDCD1_RPPA"
