source_files:
  - "modules/cellcontentmodule.R"
  - "modules/immuneinterfacemodule.R"
  - "modules/featurecorrelationmodule.R"
  - "modules/survivalmodule.R"
  - "functions/load_data.R"
  - "functions/utils.R"
  - "functions/boxplot.R"
  - "functions/heatmap.R"
  - "functions/kmplot.R"

libraries:
  - "shinythemes"
  - "bigrquery"
  - "plotly"
  - "heatmaply"
  - "survival"
  - "survminer"
  - "googlesheets"

nice_names:
  "Subtype_Immune_Model_Based": "Immune Subtypes"
  "OS_time": "OS Time"
  "leukocyte_fraction": "Leukocyte Fraction"
  "mutationrate_nonsilent_per_Mb": "Mutation Rate, Non-Silent"
  "indel_neoantigen_num": "Indel Neoantigens"
  "numberOfImmunogenicMutation": "SNV Neoantigens"
  "StemnessScoreRNA": "Stemness Score RNA"
  "Neutrophils.Aggregate2": "Neutrophils"
  "Eosinophils.Aggregate2": "Eosinophils"
  "Mast_cells.Aggregate2": "Mast cells"
  "Dendritic_cells.Aggregate2": "Dendritic cells"
  "Macrophage.Aggregate2": "Macrophage"
  "NK_cells.Aggregate2": "NK cells"
  "B_cells.Aggregate2": "B cells"
  "T_cells_CD8.Aggregate2": "CD8 T cells"
  "T_cells_CD4.Aggregate2": "CD4 T cells"
  "CHANG_CORE_SERUM_RESPONSE_UP": "Wound response"
  "CSF1_response": "Macrophage"
  "LIexpression_score": "Leukocyte infiltration"
  "Module3_IFN_score": "Interferon gamma"
  "TGFB_score_21050467": "TGF-beta"
  "C1": "C1"
  "C2": "C2"
  "C3": "C3"
  "C4": "C4"
  "C5": "C5"
  "C6": "C6"
  "CD274_RNASeq": "PD1L1 (CD274) RNA-seq"
  "CD68_RNASeq": "CD68 RNA-seq"
  "CD8A_RNASeq": "CD8A RNA-seq"
  "CTLA4_RNASeq": "CTLA4 RNA-seq"
  "PDCD1_RNASeq": "PDCD1 RNA-seq"
  "TREM1_RNASeq": "TREM1 RNA-seq"
  "CD274_RPPA": "PD1L1 (CD274) RPPA"
  "CTLA4_RPPA": "CTLA4 RPPA"
  "LCK_RPPA": "LCK RPPA"
  "PDCD1_RPPA": "PDCD1 RPPA"
  
Leukocytes:
   - "Neutrophils.Aggregate2"
   - "Eosinophils.Aggregate2"
   - "Mast_cells.Aggregate2"
   - "Dendritic_cells.Aggregate2"
   - "Macrophage.Aggregate2"
   - "NK_cells.Aggregate2"
   - "B_cells.Aggregate2"
   - "T_cells_CD8.Aggregate2"
   - "T_cells_CD4.Aggregate2"
   
Gene Sets:   
   - "CHANG_CORE_SERUM_RESPONSE_UP"
   - "CSF1_response"
   - "LIexpression_score"
   - "Module3_IFN_score"
   - "TGFB_score_21050467"
   
Genes RNA-seq & RPPA:
   - "CD274_RNASeq"
   - "CD68_RNASeq"
   - "CD8A_RNASeq"
   - "CTLA4_RNASeq"
   - "PDCD1_RNASeq"
   - "TREM1_RNASeq"
   - "CD274_RPPA"
   - "CTLA4_RPPA"
   - "LCK_RPPA"
   - "PDCD1_RPPA"
