source_files:
  - "modules/cellcontentmodule.R"
  - "modules/immuneinterfacemodule.R"
  - "modules/featurecorrelationmodule.R"
  - "modules/survivalmodule.R"
  - "modules/immnomodulatormodule.R"
  - "modules/immnomodulatormodule2.R"
  - "functions/load_data.R"
  - "functions/utils.R"
  - "functions/boxplot.R"
  - "functions/heatmap.R"
  - "functions/kmplot.R"

libraries:
  - "shinythemes"
  - "bigrquery"
  - "plotly"
  - "heatmaply"
  - "survival"
  - "survminer"
  - "googlesheets"
  
cell_content_local:
  - "leukocyte_fraction"
  - "Lymphocytes.Aggregate1"
  - "T.cells.CD8"
  - "T_cells_CD4.Aggregate2"
  - "Macrophage.Aggregate1"

cell_content_bq:
  - "leukocyte_fraction"
  - "Lymphocytes.Aggregate1"
  - "T_cells_CD8"
  - "T_cells_CD4_Aggregate2"
  - "Macrophage_Aggregate1"
 
diversity_metric_choices:
  - "Evenness"
  - "Shannon"
  - "Richness"

receptor_type_choices:
  - "TCR"
  - "BCR"
  
immunomodulator_groups:
  - "Gene_Family"
  - "Super_Category"
  - "Immune_Checkpoint"
  - "Function"