source_files:
  - "modules/cellcontentmodule.R"
  - "modules/immuneinterfacemodule.R"
  - "modules/featurecorrelationmodule.R"
  - "modules/survivalmodule.R"
  - "functions/load_data.R"
  - "functions/utils.R"
  - "functions/boxplot.R"
  - "functions/heatmap.R"
  - "functions/kmplot.R"

libraries:
  - "shinythemes"
  - "bigrquery"
  - "plotly"
  - "heatmaply"
  - "survival"
  - "survminer"
  - "googlesheets"