DB_NAME <- Sys.getenv("DB_NAME", unset = "iatlas_shiny_test")
DB_HOST <- Sys.getenv("DB_HOST", unset = "localhost")
DB_PORT <- Sys.getenv("DB_PORT", unset = "5432")
DB_USER <- Sys.getenv("DB_USER", unset = "postgres")
DB_PW <- Sys.getenv("DB_PW", unset = "docker")
